In [1]:
import pandas as pd


# Replace 'filename.csv' with the path to your CSV file
df = pd.read_csv('/kaggle/input/mlolympiadbd2024/train.csv')

In [2]:
columns_to_drop = ['WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm','Date']  # List of column names to drop
df.drop(columns=columns_to_drop, inplace=True)

In [3]:
df.head()

,Temp9am,Temp3pm,MinTemp,MaxTemp,Rainfall,RainToday,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,ID
0,20.7,20.9,19.5,22.4,15.6,Yes,6.2,0.0,17,20,92,84,1017.6,1017.4,8,8,1
1,22.4,24.8,19.5,25.6,6.0,Yes,3.4,2.7,9,13,83,73,1017.9,1016.4,7,7,2
2,23.5,23.0,21.6,24.5,6.6,Yes,2.4,0.1,17,2,88,86,1016.7,1015.6,7,8,3
3,21.4,20.9,20.2,22.8,18.8,Yes,2.2,0.0,22,20,83,90,1014.2,1011.8,8,8,4
4,22.5,25.5,19.7,25.7,77.4,Yes,4.8,0.0,11,6,88,74,1008.3,1004.8,8,8,5

In [4]:
df.replace(to_replace={'RainToday': {'No': '0', 'Yes': '1'}}, inplace=True)

In [5]:
df.head()

,Temp9am,Temp3pm,MinTemp,MaxTemp,Rainfall,RainToday,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,ID
0,20.7,20.9,19.5,22.4,15.6,1,6.2,0.0,17,20,92,84,1017.6,1017.4,8,8,1
1,22.4,24.8,19.5,25.6,6.0,1,3.4,2.7,9,13,83,73,1017.9,1016.4,7,7,2
2,23.5,23.0,21.6,24.5,6.6,1,2.4,0.1,17,2,88,86,1016.7,1015.6,7,8,3
3,21.4,20.9,20.2,22.8,18.8,1,2.2,0.0,22,20,83,90,1014.2,1011.8,8,8,4
4,22.5,25.5,19.7,25.7,77.4,1,4.8,0.0,11,6,88,74,1008.3,1004.8,8,8,5

In [6]:
columns_to_drop = ['ID']  # List of column names to drop
df.drop(columns=columns_to_drop, inplace=True)

In [7]:
df.head()

,Temp9am,Temp3pm,MinTemp,MaxTemp,Rainfall,RainToday,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm
0,20.7,20.9,19.5,22.4,15.6,1,6.2,0.0,17,20,92,84,1017.6,1017.4,8,8
1,22.4,24.8,19.5,25.6,6.0,1,3.4,2.7,9,13,83,73,1017.9,1016.4,7,7
2,23.5,23.0,21.6,24.5,6.6,1,2.4,0.1,17,2,88,86,1016.7,1015.6,7,8
3,21.4,20.9,20.2,22.8,18.8,1,2.2,0.0,22,20,83,90,1014.2,1011.8,8,8
4,22.5,25.5,19.7,25.7,77.4,1,4.8,0.0,11,6,88,74,1008.3,1004.8,8,8

In [8]:
Y_train=df['RainToday']

In [9]:
Y_train

0       1
1       1
2       1
3       1
4       1
       ..
2611    0
2612    0
2613    0
2614    0
2615    0
Name: RainToday, Length: 2616, dtype: object

In [10]:
X_train=df.drop(['RainToday'],axis=1)

In [11]:
X_train

,Temp9am,Temp3pm,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm
0,20.7,20.9,19.5,22.4,15.6,6.2,0.0,17,20,92,84,1017.6,1017.4,8,8
1,22.4,24.8,19.5,25.6,6.0,3.4,2.7,9,13,83,73,1017.9,1016.4,7,7
2,23.5,23.0,21.6,24.5,6.6,2.4,0.1,17,2,88,86,1016.7,1015.6,7,8
3,21.4,20.9,20.2,22.8,18.8,2.2,0.0,22,20,83,90,1014.2,1011.8,8,8
4,22.5,25.5,19.7,25.7,77.4,4.8,0.0,11,6,88,74,1008.3,1004.8,8,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2611,15.1,20.1,11.6,20.5,0.0,3.0,4.3,9,17,87,44,1019.7,1015.1,7,6
2612,14.6,18.5,10.6,20.8,0.0,2.8,9.2,22,20,48,43,1019.8,1018.9,3,5
2613,13.0,20.1,9.0,20.3,0.0,4.2,10.8,13,15,60,31,1022.7,1017.9,1,2
2614,12.1,18.1,8.3,18.7,0.0,3.6,10.8,20,22,52,44,1020.3,1017.5,1,3
2615,13.9,18.4,9.6,19.7,0.0,4.8,10.9,15,22,48,39,1017.3,1013.8,1,2

In [12]:
from sklearn.svm import SVC
svc=SVC()
svc.fit(X_train,Y_train)

SVC()

In [13]:
# Replace 'filename.csv' with the path to your CSV file
dftest2 = pd.read_csv('/kaggle/input/mlolympiadbd2024/test.csv')

In [14]:
columns_to_drop = ['WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm','Date','ID']  # List of column names to drop
dftest2.drop(columns=columns_to_drop, inplace=True)

In [15]:
dftest2

,Temp9am,Temp3pm,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm
0,12.7,17.0,9.0,19.7,0.0,3.2,10.8,17,13,50,39,1015.8,1013.3,1,1
1,11.9,18.6,8.0,18.8,0.0,4.0,10.4,11,19,61,46,1018.0,1012.0,5,1
2,14.4,20.6,11.2,20.8,2.8,5.6,8.0,20,24,69,28,1006.0,1005.6,3,6
3,13.7,18.3,12.5,19.5,20.4,4.0,5.7,19,20,92,54,1021.5,1020.5,7,2
4,15.2,18.7,11.5,21.7,0.0,2.8,9.3,17,24,68,53,1022.3,1019.6,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650,10.5,17.9,8.6,19.6,0.0,2.0,7.8,22,20,73,52,1025.9,1025.3,2,2
651,11.0,18.7,9.3,19.2,0.0,2.0,9.2,20,7,78,53,1028.5,1024.6,2,2
652,10.2,17.3,9.4,17.7,0.0,2.4,2.7,15,13,85,56,1020.8,1015.0,6,6
653,12.4,19.0,10.1,19.3,0.0,1.4,9.3,17,19,56,35,1017.3,1015.1,5,2
654,9.4,18.8,7.6,19.3,0.0,3.4,9.4,13,13,73,32,1018.6,1015.4,1,1

In [16]:
y_pred = svc.predict(dftest2)

In [17]:
y_pred

array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0'], dtype=object)

In [18]:
results = pd.DataFrame({
    'ID': range(1, len(dftest2) + 1),
    'Predicted': y_pred
})

In [19]:
results

      ID Predicted
0      1         0
1      2         0
2      3         0
3      4         0
4      5         0
..   ...       ...
650  651         0
651  652         0
652  653         0
653  654         0
654  655         0

[655 rows x 2 columns]

In [20]:
results.replace(to_replace={'Predicted': {'0': 'No', '1': 'Yes'}}, inplace=True)

In [21]:
results

      ID Predicted
0      1        No
1      2        No
2      3        No
3      4        No
4      5        No
..   ...       ...
650  651        No
651  652        No
652  653        No
653  654        No
654  655        No

[655 rows x 2 columns]

In [22]:
results.to_csv('subset.csv', index=False)